#!/usr/bin/env bash
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' &>/dev/null
if [ $? == 0 ]
then
	SPT_ARTIST=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | egrep -A 2 "artist" | egrep -v "artist" | egrep -v "array" | cut -b 27- | cut -d '"' -f 1 | egrep -v ^$ | awk '{print tolower($0)}'`
	SPT_TITLE=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | egrep -A 1 "title" | egrep -v "title" | cut -b 44- | cut -d '"' -f 1 | egrep -v ^$ | awk '{print tolower($0)}'`
	# this small workaround replaces 'i' in song names in Kabardian language.
	# not everyone uses the original cyrillic letter 'ӏ' (palochka) because
	# it is not widely supported and not everyone uses the existing keyboard layouts :(
	# the issue is that i am using all-lowercase style on my bars, so lowercase 'i'
	# doesn't look like 'ӏ', while uppercase 'I' is pretty similar to 'ӏ'.
	INFO=($SPT_ARTIST -)
	echo $SPT_TITLE | grep "[а-я]" > /dev/null && INFO+=("$(echo $SPT_TITLE | sed -E "s/i/ӏ/")") || INFO+=($SPT_TITLE)
	echo ${INFO[@]}
else
	echo ''
fi
