#!/usr/bin/env bash
gr="\x1B[32m"
ye="\x1B[33m"
re="\x1B[0m"

function lock() {
  bg="/tmp/screen.png"
  scrot $bg
  convert $bg -blur 0x12 $bg
  i3lock -u -i $bg && rm $bg
}

case $1 in
lock)
  lock
  ;;
logout)
  i3-msg exit
  ;;
sleep)
  lock && systemctl suspend
  ;;
hibernate)
  lock && systemctl hibernate
  ;;
reboot)
  systemctl reboot
  ;;
shutdown)
  systemctl poweroff
  ;;
*)
  echo -e "$gr""i3exit$re 1.0.1"
  echo "Llathasa Veleth <llathasa@outlook.com>"
  echo -e "i3 exit manager.\n"
  echo -e "$ye""USAGE:$re\n\t""i3exit $gr<lock|logout|sleep|hibernate|reboot|shutdown>$re"
  exit 1
  ;;
esac
