#!/usr/bin/env bash
if [ $# == 0 ];
then
  mod='def'
else
  mod=$1
fi

r='\033[0;41m'
g='\033[0;42m'
y='\033[0;43m'
b='\033[0;44m'
m='\033[0;45m'
c='\033[0;46m'
wh='\033[0;47m'
gr='\033[0;107m'
re='\033[0m'

printf "\n"
if [ $mod == 'comb' ];
then
  printf "  $r +    + $re $g +    + $re $y +    + $re $b +    + $re $m +    + $re $c +    + $re\n"
  printf "  $r +    + $re $g +    + $re $y +    + $re $b +    + $re $m +    + $re $c +    + $re\n"
elif [ $mod == 'def' ];
then
  printf "  $r        $re $g        $re $y        $re $b        $re $m        $re $c        $re\n"
  printf "  $r        $re $g        $re $y        $re $b        $re $m        $re $c        $re\n"
fi
printf "  $wh      $re$gr  $re $wh      $re$gr  $re $wh      $re$gr  $re $wh      $re$gr  $re $wh      $re$gr  $re $wh      $re$gr  $re\n"
